// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8li6Sd9VCOXYLtoF_uyDB4eUeiAGGOf4',
    appId: '1:478804619543:web:3e91a0737a76666d5e0752',
    messagingSenderId: '478804619543',
    projectId: 'tapak-tani',
    authDomain: 'tapak-tani.firebaseapp.com',
    storageBucket: 'tapak-tani.firebasestorage.app',
    measurementId: 'G-Q68JMZCGJH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCeR2C97KzioPEFWggKIUcsS9VX9P2NCJA',
    appId: '1:478804619543:android:0352de76c4ea91665e0752',
    messagingSenderId: '478804619543',
    projectId: 'tapak-tani',
    storageBucket: 'tapak-tani.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB8li6Sd9VCOXYLtoF_uyDB4eUeiAGGOf4',
    appId: '1:478804619543:web:74e17071b267f2a25e0752',
    messagingSenderId: '478804619543',
    projectId: 'tapak-tani',
    authDomain: 'tapak-tani.firebaseapp.com',
    storageBucket: 'tapak-tani.firebasestorage.app',
    measurementId: 'G-7MRM9J7P0S',
  );
}
